### ISSUE TITLE
Sourceforge vs git

### ISSUE THREAD

**Issue by joeytakeda** [internetshakespeare/ise2-import#6]
Is there a reason to use the sourceforge repo for the TEI style sheets versus the git? I was under the impression that the TEIC suggested using code from git rather than sourceforge, but I could be mistaken.

**Comment by martindholmes** [comment]
We shouldn't use SF any more. If there are references to SF in the code, they should be replaced with GH references. I think it's just that they're old. IIRC, the TEI still releases builds through SF for historical continuity, but that may stop at any time.

**Comment by telic** [comment]
Sorry, I just grabbed the first one I found :)  Fixed now.
